# Generated by Django 3.0.4 on 2020-03-23 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bevdir', '0002_auto_20200323_1945'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='misc',
            field=models.ManyToManyField(related_name='cocktails', to='bevdir.MiscIngredient'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='spirits',
            field=models.ManyToManyField(related_name='cocktails', to='bevdir.Spirit'),
        ),
    ]
