# Generated by Django 3.0.4 on 2020-03-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bevdir', '0003_auto_20200323_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(default=0)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='bevdir.Cocktail')),
                ('spirit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='bevdir.Spirit')),
            ],
        ),
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=10)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='bevdir.Cocktail')),
                ('misc_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misc_ingredients', to='bevdir.MiscIngredient')),
            ],
        ),
    ]
