# Generated by Django 3.0.4 on 2020-03-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bevdir', '0007_auto_20200325_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='spirit',
            name='mxb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='spirit',
            name='nc_code',
            field=models.CharField(default='x', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spirit',
            name='proof',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spirit',
            name='size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='spirit',
            name='supplier',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spirit',
            name='brandname',
            field=models.CharField(max_length=100),
        ),
    ]
