# Generated by Django 3.0.4 on 2020-03-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bevdir', '0005_auto_20200324_2313'),
        ('bevdir', '0007_auto_20200325_0234'),
    ]

    operations = [
    ]
