# Generated by Django 3.0.4 on 2020-03-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bevdir', '0008_auto_20200325_2306'),
        ('bevdir', '0008_merge_20200325_1512'),
    ]

    operations = [
    ]
