# Generated by Django 3.0.4 on 2020-03-28 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bevdir', '0010_portion_price_per_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spirit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bevdir.Spirit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
