# Generated by Django 3.0.4 on 2020-03-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bevdir', '0012_auto_20200329_2006'),
        ('bevdir', '0012_auto_20200329_1751'),
    ]

    operations = [
    ]
