# Generated by Django 3.0.4 on 2020-04-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bevdir', '0013_merge_20200330_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portion',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
