# Generated by Django 3.0.4 on 2020-04-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bevdir', '0014_auto_20200402_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscingredient',
            name='cost_per_unit',
            field=models.FloatField(default=0),
        ),
    ]
