# Generated by Django 3.0.4 on 2020-04-03 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bevdir', '0014_auto_20200402_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cocktails', to=settings.AUTH_USER_MODEL),
        ),
    ]
