# Generated by Django 3.0.4 on 2020-04-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bevdir', '0015_auto_20200403_0207'),
        ('bevdir', '0015_cocktail_user'),
    ]

    operations = [
    ]
