# Generated by Django 3.0.4 on 2020-04-05 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bevdir', '0016_merge_20200403_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='target_profit',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
